#unique ID of a specific job, may include the date to be unique
string jobID

#status of the job
string status

#description of the job type
string jobName

#payload
string payload

#definition of the Bot Team
string teamDefinitionName
teamDefinition team

#start location name and coordinates
string startLocationName
float32[] startLocation

#destination location name and coordinates
string destinationLocationName
float32[] destinationLocation

#waypoints
float32[] way_points

