#unique ID of a specific job, may include the date to be unique
string job_id

#status of the job
string status

#description of the job type
string job_name

#payload
string payload

#definition of the Bot Team
string team_definition_name
teamDefinition team

#start location name and coordinates
string start_location_name
float32[] start_location

#destination location name and coordinates
string destination_location_name
float32[] destination_location

#waypoints
float32[] way_points

